### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by zamandalee** [aguamenti/Leeway#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by rkoron007** [comment]
I need your heroku link - you can put in on your wiki home page now!

**Comment by rkoron007** [comment]
First of all looks amazing!!
- Getting a cute favicon will make our website look more professional!
- The type and buttons could use a little extra styling to make it look perfect. 
![screen shot 2018-08-13 at 9 24 13 am](https://user-images.githubusercontent.com/32436232/44044531-af78039e-9eda-11e8-80eb-7773863eff71.png)
- You could copy the workspaces button styling for your sign in button. :)

![screen shot 2018-08-13 at 9 25 51 am](https://user-images.githubusercontent.com/32436232/44044609-f82f4246-9eda-11e8-8d1b-89c4d23eaeb9.png)

- You should have a demo login button on your sign up page too for lazy recruiters.
